name: Bug Report
description: Report incorrect data, scraping failures, or other issues
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Type
      description: What kind of issue is this?
      options:
        - Incorrect price data
        - Missing cities
        - Scraper failing/timing out
        - API response format issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: |
        The price for Mumbai petrol shows 0.00 instead of the actual price...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: |
        Mumbai petrol price should show the correct value (e.g., 103.44)

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: |
        The price shows as 0.00 in prices.json

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Link to prices.json, screenshot, or other evidence
      placeholder: |
        https://raw.githubusercontent.com/SHN2004/OpenFuel/main/prices.json

        The entry shows: {"city": "Mumbai", "price": 0.00}

  - type: input
    id: date
    attributes:
      label: Date Noticed
      description: When did you first notice this issue?
      placeholder: "2025-01-08"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
